on: release
name: Check tag and release
jobs:
  github_changes:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npx github-changes -o khrtz -r my-portal -a --only-pulls --use-commit-body --for-tag upcoming
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}